# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

ARCHITECTURE = avr
BOARD_TAG = pro
BOARD_SUB = 16MHzatmega328
MONITOR_PORT = /dev/ttyUSB1
AVRDUDE_CONF = $(AVR_TOOLS_DIR)/etc/avrdude.conf
include $(ARDMK_DIR)/Arduino.mk
